spring:
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
